# Generated by Django 4.0 on 2023-03-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmainmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
