# Generated by Django 4.0 on 2023-03-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_testclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField()),
                ('products', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
